### ISSUE TITLE
Visning av Mbtiles i Qgis

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/tiny-tileserver#36]
Ønsker meg mulighet til å se .mbtiles fra maps.artsdatabanken.no i Qgis:

https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/Help

**Comment by bjornreppen** [comment]
Denne kan være på plass nå?

Bruk tilejson linkene fra https://data.artsdatabanken.no for eksempel:  https://data.artsdatabanken.no/Natur_i_Norge/Landskap/Landskapsgradient/Arealbruksintensitet/raster_gradient.3857.mbtiles?tilejson
